export const quoteCopy = {
  es: {
    title: 'Tu próximo proyecto empieza aquí.',
    intro:
      'Elige lo que necesitas y obtén una estimación clara, en pesos mexicanos.',
    automatic: 'Cotización instantánea',
    automaticDesc: 'Configura tu sitio y descarga el desglose en PDF.',
    custom: 'Proyecto a medida',
    customDesc: 'Cuéntame tu idea para revisar un alcance personalizado.',
    choose: 'Elegir modalidad',
    features: 'Diseña tu sitio',
    featuresDesc:
      'La landing es el punto de partida. Suma las funciones que necesita tu proyecto.',
    included: 'Incluido',
    requires: 'Requiere',
    client: 'Tus datos',
    fullName: 'Nombre completo',
    email: 'Correo electrónico',
    phone: 'Teléfono / WhatsApp',
    companyName: 'Empresa o proyecto',
    location: 'Ciudad y país',
    comments: 'Comentarios (opcional)',
    description: '¿Qué necesitas construir?',
    budget: 'Presupuesto estimado (MXN)',
    select: 'Selecciona un rango',
    download: 'Descargar cotización PDF',
    generating: 'Preparando PDF…',
    send: 'Enviar solicitud',
    sending: 'Enviando…',
    summary: 'Tu inversión',
    project: 'Desarrollo · pago único',
    monthly: 'Mantenimiento mensual',
    subtotal: 'Subtotal',
    tax: 'IVA (16%)',
    total: 'Total con IVA',
    note: 'Estimación orientativa, válida por 30 días. El alcance y los plazos se confirman antes de contratar.',
    local:
      'El PDF se genera en tu navegador. Tus datos no se envían ni se guardan; para recibir seguimiento utiliza Proyecto a medida.',
    consent:
      'Autorizo el envío de estos datos a Marcos GZZ para responder a mi solicitud.',
    sent: 'Solicitud enviada',
    sentDesc:
      'Recibí los detalles de tu proyecto. Me pondré en contacto contigo usando los datos que compartiste.',
    done: 'Tu PDF está listo',
    doneDesc:
      'Se inició la descarga. Guarda el documento y envíamelo si deseas revisar la propuesta.',
    again: 'Volver al cotizador',
    error:
      'No pudimos completar la operación. Intenta de nuevo o escríbeme por correo.',
    unavailable:
      'El envío por correo aún no está disponible. Escríbeme directamente.',
    rate: 'Hay demasiadas solicitudes. Espera unos minutos y vuelve a intentar.',
    contact: 'Escríbeme',
    reference: 'Referencia',
    date: 'Fecha',
    quote: 'Cotización de desarrollo web',
    details: 'Alcance seleccionado',
    hosting: 'Hosting básico',
    labels: {
      landing: 'Landing page',
      formLanding: 'Formulario en landing',
      about: 'Nosotros',
      contact: 'Página de contacto',
      contactForm: 'Formulario de contacto',
      catalog: 'Catálogo de productos',
      ecommerce: 'Tienda online',
      wishlist: 'Lista de deseos',
      coupons: 'Cupones',
      reviews: 'Reseñas',
      portfolio: 'Portafolio',
      blog: 'Blog',
      ai: 'Chatbot con IA',
      aiPremium: 'IA premium',
    },
    descriptions: {
      formLanding: 'Captura de consultas desde la página principal.',
      about: 'Historia, equipo y presentación de la empresa.',
      contact: 'Información de contacto y mapa.',
      contactForm: 'Consultas por correo. Añade mantenimiento mensual.',
      catalog: 'Productos, categorías, filtros y administración.',
      ecommerce: 'Incluye catálogo, carrito, pagos y gestión de pedidos.',
      wishlist: 'Permite guardar productos favoritos.',
      coupons: 'Descuentos y promociones para tu tienda.',
      reviews: 'Opiniones y valoraciones de productos.',
      portfolio: 'Galería de trabajos con administración.',
      blog: 'Artículos, categorías y buscador.',
      ai: 'Asistente entrenado con información de tu negocio.',
      aiPremium:
        'Personalización avanzada y eliminación de marca. Añade mantenimiento mensual.',
    },
  },
  en: {
    title: 'Your next project starts here.',
    intro: 'Choose what you need and get a clear estimate in Mexican pesos.',
    automatic: 'Instant quote',
    automaticDesc: 'Configure your website and download an itemized PDF.',
    custom: 'Custom project',
    customDesc: 'Tell me about your idea so we can define a tailored scope.',
    choose: 'Choose a quote type',
    features: 'Build your website',
    featuresDesc:
      'A landing page is the starting point. Add the features your project needs.',
    included: 'Included',
    requires: 'Requires',
    client: 'Your details',
    fullName: 'Full name',
    email: 'Email address',
    phone: 'Phone / WhatsApp',
    companyName: 'Company or project',
    location: 'City and country',
    comments: 'Comments (optional)',
    description: 'What would you like to build?',
    budget: 'Estimated budget (MXN)',
    select: 'Select a range',
    download: 'Download quote PDF',
    generating: 'Preparing PDF…',
    send: 'Send request',
    sending: 'Sending…',
    summary: 'Your investment',
    project: 'Development · one-time payment',
    monthly: 'Monthly maintenance',
    subtotal: 'Subtotal',
    tax: 'VAT (16%)',
    total: 'Total including VAT',
    note: 'Indicative estimate, valid for 30 days. Scope and timing are confirmed before contracting.',
    local:
      'The PDF is generated in your browser. Your details are neither sent nor stored; choose Custom project to request a response.',
    consent:
      'I authorize sending these details to Marcos GZZ to respond to my request.',
    sent: 'Request sent',
    sentDesc:
      'I have received your project details and will contact you using the information you provided.',
    done: 'Your PDF is ready',
    doneDesc:
      'The download has started. Save the document and send it to me if you would like to discuss the proposal.',
    again: 'Back to the calculator',
    error: 'We could not complete the operation. Try again or email me.',
    unavailable:
      'Email submission is not available yet. Please email me directly.',
    rate: 'Too many requests. Wait a few minutes and try again.',
    contact: 'Email me',
    reference: 'Reference',
    date: 'Date',
    quote: 'Web development quote',
    details: 'Selected scope',
    hosting: 'Basic hosting',
    labels: {
      landing: 'Landing page',
      formLanding: 'Landing page form',
      about: 'About us',
      contact: 'Contact page',
      contactForm: 'Contact form',
      catalog: 'Product catalog',
      ecommerce: 'Online store',
      wishlist: 'Wishlist',
      coupons: 'Coupons',
      reviews: 'Reviews',
      portfolio: 'Portfolio',
      blog: 'Blog',
      ai: 'AI chatbot',
      aiPremium: 'Premium AI',
    },
    descriptions: {
      formLanding: 'Receive inquiries from your home page.',
      about: 'Company story, team and introduction.',
      contact: 'Contact information and map.',
      contactForm: 'Email inquiries. Adds monthly maintenance.',
      catalog: 'Products, categories, filters and administration.',
      ecommerce: 'Includes catalog, cart, payments and order management.',
      wishlist: 'Save favorite products.',
      coupons: 'Discounts and promotions for your store.',
      reviews: 'Product feedback and ratings.',
      portfolio: 'Managed project gallery.',
      blog: 'Articles, categories and search.',
      ai: 'Assistant trained on your business information.',
      aiPremium:
        'Advanced customization and removal of branding. Adds monthly maintenance.',
    },
  },
  pt: {
    title: 'Seu próximo projeto começa aqui.',
    intro:
      'Escolha o que precisa e obtenha uma estimativa clara em pesos mexicanos.',
    automatic: 'Orçamento instantâneo',
    automaticDesc: 'Configure seu site e baixe o detalhamento em PDF.',
    custom: 'Projeto personalizado',
    customDesc: 'Conte sua ideia para definirmos um escopo personalizado.',
    choose: 'Escolher modalidade',
    features: 'Monte seu site',
    featuresDesc:
      'A landing page é o ponto de partida. Adicione as funções de que seu projeto precisa.',
    included: 'Incluído',
    requires: 'Requer',
    client: 'Seus dados',
    fullName: 'Nome completo',
    email: 'E-mail',
    phone: 'Telefone / WhatsApp',
    companyName: 'Empresa ou projeto',
    location: 'Cidade e país',
    comments: 'Comentários (opcional)',
    description: 'O que você precisa construir?',
    budget: 'Orçamento estimado (MXN)',
    select: 'Selecione uma faixa',
    download: 'Baixar orçamento PDF',
    generating: 'Preparando PDF…',
    send: 'Enviar solicitação',
    sending: 'Enviando…',
    summary: 'Seu investimento',
    project: 'Desenvolvimento · pagamento único',
    monthly: 'Manutenção mensal',
    subtotal: 'Subtotal',
    tax: 'IVA (16%)',
    total: 'Total com IVA',
    note: 'Estimativa indicativa, válida por 30 dias. O escopo e os prazos são confirmados antes da contratação.',
    local:
      'O PDF é gerado no seu navegador. Seus dados não são enviados nem armazenados; escolha Projeto personalizado para solicitar uma resposta.',
    consent:
      'Autorizo o envio destes dados a Marcos GZZ para responder à minha solicitação.',
    sent: 'Solicitação enviada',
    sentDesc:
      'Recebi os detalhes do seu projeto e entrarei em contato usando os dados que você informou.',
    done: 'Seu PDF está pronto',
    doneDesc:
      'O download foi iniciado. Salve o documento e envie para mim se quiser conversar sobre a proposta.',
    again: 'Voltar ao calculador',
    error:
      'Não foi possível concluir a operação. Tente novamente ou envie um e-mail.',
    unavailable:
      'O envio por e-mail ainda não está disponível. Entre em contato diretamente.',
    rate: 'Muitas solicitações. Aguarde alguns minutos e tente novamente.',
    contact: 'Envie um e-mail',
    reference: 'Referência',
    date: 'Data',
    quote: 'Orçamento de desenvolvimento web',
    details: 'Escopo selecionado',
    hosting: 'Hospedagem básica',
    labels: {
      landing: 'Landing page',
      formLanding: 'Formulário na landing',
      about: 'Sobre nós',
      contact: 'Página de contato',
      contactForm: 'Formulário de contato',
      catalog: 'Catálogo de produtos',
      ecommerce: 'Loja virtual',
      wishlist: 'Lista de desejos',
      coupons: 'Cupons',
      reviews: 'Avaliações',
      portfolio: 'Portfólio',
      blog: 'Blog',
      ai: 'Chatbot com IA',
      aiPremium: 'IA premium',
    },
    descriptions: {
      formLanding: 'Receba consultas pela página principal.',
      about: 'História, equipe e apresentação da empresa.',
      contact: 'Informações de contato e mapa.',
      contactForm: 'Consultas por e-mail. Adiciona manutenção mensal.',
      catalog: 'Produtos, categorias, filtros e administração.',
      ecommerce: 'Inclui catálogo, carrinho, pagamentos e gestão de pedidos.',
      wishlist: 'Salve produtos favoritos.',
      coupons: 'Descontos e promoções para sua loja.',
      reviews: 'Opiniões e avaliações de produtos.',
      portfolio: 'Galeria de trabalhos com administração.',
      blog: 'Artigos, categorias e busca.',
      ai: 'Assistente treinado com informações do seu negócio.',
      aiPremium:
        'Personalização avançada e remoção de marca. Adiciona manutenção mensal.',
    },
  },
};
export type FeatureKey = keyof typeof quoteCopy.es.descriptions;
